# Generated by Django 2.2.7 on 2019-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20191114_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='password',
            new_name='access_key',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
